### ISSUE TITLE
请问领宝箱id如何修改

### ISSUE THREAD

**Issue by Angus1996** [Vincentlz/Small-video-speed#9]
代码里有一段
if (textContains("开宝箱").exists()) {
        id("b9b").click()//领宝箱按钮id不定时随机变化，失效请修改
        className("android.view.View").clickable(true).depth(12).findOne().click()
        dytimes(3000, 5000)
        back();        
    }
请问这个id如何修改？

**Comment by Vincentlz** [comment]
查看布局范围分析，点击对应的按钮-查看控件id信息

**Comment by Angus1996** [comment]
> 查看布局范围分析，点击对应的按钮-查看控件id信息
